### ISSUE TITLE
multiple books - widget says that the account was deleted 

### ISSUE THREAD

**Issue by nikopp** [codinguser/gnucash-android#579]
#### Expected behaviour
The widget shows the amount of the account.

#### Actual behaviour
The widget says that the account was deleted.

#### Steps to reproduce the behaviour
1. Use several books. 
2. Create a widget. 
3. Switch between books.
4. Do some other stuff / wait.
5. Notice the message that is shown by the widget.

#### Software specifications
* GnuCash Android version: 2.1.1 beta
* System Android version: 6.0.1
* Device type: Sony Xperia Z3 compact

**Comment by rivaldi8** [comment]
@codinguser This is fixed in ff894a5, isn't it?

**Comment by rivaldi8** [comment]
Ok, I've verified it's fixed by that commit. It'll appear fixed in version 2.1.3. You may need to remove the widget and add it again for it to work.

**Comment by codinguser** [comment]
@rivaldi8 yes, that commit adds support for selecting the book when adding a widget

**Comment by nikopp** [comment]
@rivaldi8 The problem is still present in 2.1.3. I did remove the widgets and added them again.
But it happens only sometimes, not as often as with 2.1.2.
And the widgets start working again without recreating.
I couldn't find out why they stop or why restart working. There seems to be no obvious trigger.
I also had the case that only some widgets for one book show the message while others still work fine.

Do you want to reopen this bug or should I file a new one?

**Comment by rivaldi8** [comment]
> I also had the case that only some widgets for one book show the message while others still work fine.

This makes me think we are dealing with a different, although similar, bug. If you don't mind, I'll rather have it filed as new bug. Thanks!

**Comment by nikopp** [comment]
I filed #613.
