### ISSUE TITLE
[Unverified] Crash when importing GNC XML from Gnucash desktop v3.2

### ISSUE THREAD

**Issue by codinguser** [codinguser/gnucash-android#820]
Uesr report
#### Steps to reproduce the behaviour
1. Export Gnucash XML in Gnucash desktop
2. Import into Gnucash Android

#### Expected behaviour
3. Import works and Accounts list is displayed

#### Actual behaviour
3. App crashes

#### Software specifications
* GnuCash Android version:
* System Android version:
* Device type:

**Comment by CardcaptorRLH85** [comment]
I'm having this same issue with GnuCash desktop version 3.5.

- GnuCash Android version: 2.4.0
- System Android version: 9
- Device Type: Samsung Galaxy S10+ US Sprint

**Comment by albelixpd** [comment]
I have same problem with gnucash desktop v.3.5.
When import xml file in gnucash 2.4 android version, have a generic "import file error"

**Comment by albelixpd** [comment]
Problem seem solved with Gnucash desktop v. 3.6 - 29/06/2019 (you have to open xml compressed file and overwrite it).

**Comment by adl1995** [comment]
@albelixpd I'm still facing this issue. How do you mean to overwrite the XML file before importing it to Android?

**Comment by albelixpd** [comment]
@adl1995 I meant this:
- Open gnucash desktop 3.6
- Open xml file (edited or created with 3.5 Destop version)
- Save as file, overwriting old file.
- Copy file on android e open it with gnucash for android.

**Comment by codinguser** [comment]
So can this issue be now closed?

**Comment by CardcaptorRLH85** [comment]
> So can this issue be now closed?

As far as I can tell, yes.  I'm no longer having this issue.
